repos:
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
        - id: flake8
          additional_dependencies: [flake8-blind-except, flake8-bugbear, flake8-comprehensions,
            flake8-debugger, flake8-docstrings, flake8-isort, flake8-polyfill, flake8-pytest,
            flake8-quotes, yesqa]
          language_version: python3.8
          args: ['--config=setup.cfg']
    - repo: https://github.com/timothycrosley/isort
      rev: v5.4.2
      hooks:
        - id: isort
          language_version: python3.8
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.770
      hooks:
        - id: mypy
          language_version: python3.8
